//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapok.View.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataPage() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kapok.View.Resources.DataPage", typeof(DataPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .. so that I can fix the validation errors ähnelt.
        /// </summary>
        public static string AskRevertChangesDueToValidationErrorsDialog_GoBack_Description {
            get {
                return ResourceManager.GetString("AskRevertChangesDueToValidationErrorsDialog_GoBack_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go back ähnelt.
        /// </summary>
        public static string AskRevertChangesDueToValidationErrorsDialog_GoBack_Label {
            get {
                return ResourceManager.GetString("AskRevertChangesDueToValidationErrorsDialog_GoBack_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There exist validation errors. Before you can go on, you need to fix the validation errors. ähnelt.
        /// </summary>
        public static string AskRevertChangesDueToValidationErrorsDialog_Message {
            get {
                return ResourceManager.GetString("AskRevertChangesDueToValidationErrorsDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Revert all my changes and go on ähnelt.
        /// </summary>
        public static string AskRevertChangesDueToValidationErrorsDialog_RevertChanges_Description {
            get {
                return ResourceManager.GetString("AskRevertChangesDueToValidationErrorsDialog_RevertChanges_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Revert changes ähnelt.
        /// </summary>
        public static string AskRevertChangesDueToValidationErrorsDialog_RevertChanges_Label {
            get {
                return ResourceManager.GetString("AskRevertChangesDueToValidationErrorsDialog_RevertChanges_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validation errors exist ähnelt.
        /// </summary>
        public static string AskRevertChangesDueToValidationErrorsDialog_Title {
            get {
                return ResourceManager.GetString("AskRevertChangesDueToValidationErrorsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        public static string CreateNewEntryCommand_Name {
            get {
                return ResourceManager.GetString("CreateNewEntryCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Concurrency violation error ähnelt.
        /// </summary>
        public static string DbUpdateConcurrencyException_MessageBox_Caption {
            get {
                return ResourceManager.GetString("DbUpdateConcurrencyException_MessageBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update concurrency violation is encountered while saving to the database.
        ///
        ///A concurrency violation occurs when an unexpected number of rows are affected during save.
        ///This is usually because the data in the database has been modified since it was loaded into memory. ähnelt.
        /// </summary>
        public static string DbUpdateConcurrencyException_MessageBox_Text {
            get {
                return ResourceManager.GetString("DbUpdateConcurrencyException_MessageBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database error ähnelt.
        /// </summary>
        public static string DbUpdateException_MessageBox_Caption {
            get {
                return ResourceManager.GetString("DbUpdateException_MessageBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database error:
        ///{0} ähnelt.
        /// </summary>
        public static string DbUpdateException_MessageBox_Text {
            get {
                return ResourceManager.GetString("DbUpdateException_MessageBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string DeleteEntryCommand_Name {
            get {
                return ResourceManager.GetString("DeleteEntryCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duplicated entry exception ähnelt.
        /// </summary>
        public static string DuplicatedEntryException_MessageBox_Caption {
            get {
                return ResourceManager.GetString("DuplicatedEntryException_MessageBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duplicated entry exception:
        ///{0} ähnelt.
        /// </summary>
        public static string DuplicatedEntryException_MessageBox_Text {
            get {
                return ResourceManager.GetString("DuplicatedEntryException_MessageBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Editable ähnelt.
        /// </summary>
        public static string Editable {
            get {
                return ResourceManager.GetString("Editable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gets or sets the information if the list is editable. Note: This can be overridden by data in the TableData property. See IsEditable as well. ähnelt.
        /// </summary>
        public static string Editable_Description {
            get {
                return ResourceManager.GetString("Editable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string EditModeToggleCommand_Name {
            get {
                return ResourceManager.GetString("EditModeToggleCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is editable ähnelt.
        /// </summary>
        public static string IsEditable {
            get {
                return ResourceManager.GetString("IsEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Identifies if the list is editable. ähnelt.
        /// </summary>
        public static string IsEditable_Description {
            get {
                return ResourceManager.GetString("IsEditable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage ähnelt.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page ähnelt.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string RefreshCommand_Description {
            get {
                return ResourceManager.GetString("RefreshCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        public static string RefreshCommand_Name {
            get {
                return ResourceManager.GetString("RefreshCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save all current changes to the database ähnelt.
        /// </summary>
        public static string SaveDataCommand_Description {
            get {
                return ResourceManager.GetString("SaveDataCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string SaveDataCommand_Name {
            get {
                return ResourceManager.GetString("SaveDataCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There exist entries with validation errors. You have to solve those validation errors first before you can continue. ähnelt.
        /// </summary>
        public static string ValidationErrorExist_Message_Text {
            get {
                return ResourceManager.GetString("ValidationErrorExist_Message_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validation errors exist ähnelt.
        /// </summary>
        public static string ValidationErrorExist_Message_Title {
            get {
                return ResourceManager.GetString("ValidationErrorExist_Message_Title", resourceCulture);
            }
        }
    }
}
