//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapok.View.Resources.Data {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataSetView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataSetView() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kapok.View.Resources.Data.DataSetView", typeof(DataSetView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string ClearUserFilterCommand_Description {
            get {
                return ResourceManager.GetString("ClearUserFilterCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear filter ähnelt.
        /// </summary>
        public static string ClearUserFilterCommand_Name {
            get {
                return ResourceManager.GetString("ClearUserFilterCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The collection change action Replace is currently not supported in a TableDataViewModel. ähnelt.
        /// </summary>
        public static string CollectionChangeActionReplaceNotSupported {
            get {
                return ResourceManager.GetString("CollectionChangeActionReplaceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The database context member {0} could not be found. ähnelt.
        /// </summary>
        public static string Constructor_DbContextMemberNotFound {
            get {
                return ResourceManager.GetString("Constructor_DbContextMemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a new entry ähnelt.
        /// </summary>
        public static string CreateNewEntryCommand_Description {
            get {
                return ResourceManager.GetString("CreateNewEntryCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New entry ähnelt.
        /// </summary>
        public static string CreateNewEntryCommand_Name {
            get {
                return ResourceManager.GetString("CreateNewEntryCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete the selected entry. ähnelt.
        /// </summary>
        public static string DeleteEntryCommand_Description {
            get {
                return ResourceManager.GetString("DeleteEntryCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete entry ähnelt.
        /// </summary>
        public static string DeleteEntryCommand_Name {
            get {
                return ResourceManager.GetString("DeleteEntryCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can not create new entry while the current entry has validation errors. Please solve these validation errors first. ähnelt.
        /// </summary>
        public static string Error_CreateNewEntryWhileCurrentHasValidationError_Message {
            get {
                return ResourceManager.GetString("Error_CreateNewEntryWhileCurrentHasValidationError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error_CreateNewEntryWhileCurrentHasValidationError_Title {
            get {
                return ResourceManager.GetString("Error_CreateNewEntryWhileCurrentHasValidationError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string FilterVisibleToggleCommand_Description {
            get {
                return ResourceManager.GetString("FilterVisibleToggleCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        public static string FilterVisibleToggleCommand_Name {
            get {
                return ResourceManager.GetString("FilterVisibleToggleCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The method {0} is not supported for in-memory tables. ähnelt.
        /// </summary>
        public static string MethodNotSupportForInMemoryTable {
            get {
                return ResourceManager.GetString("MethodNotSupportForInMemoryTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not determine parameter entityService neither by parameter nor from the data domain. DataSetView: {0} ähnelt.
        /// </summary>
        public static string ParameterEntityServiceNotDetermined {
            get {
                return ResourceManager.GetString("ParameterEntityServiceNotDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter {0} must be of the type {1}. ähnelt.
        /// </summary>
        public static string ParameterMustBeOfType {
            get {
                return ResourceManager.GetString("ParameterMustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string SortAscendingCommand_Description {
            get {
                return ResourceManager.GetString("SortAscendingCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort up ähnelt.
        /// </summary>
        public static string SortAscendingCommand_Name {
            get {
                return ResourceManager.GetString("SortAscendingCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string SortDescendingCommand_Description {
            get {
                return ResourceManager.GetString("SortDescendingCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort down ähnelt.
        /// </summary>
        public static string SortDescendingCommand_Name {
            get {
                return ResourceManager.GetString("SortDescendingCommand_Name", resourceCulture);
            }
        }
    }
}
